apiVersion: apps/v1
kind: Deployment
metadata:
  name: elk-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elk
  template:
    metadata:
      labels:
        app: elk
    spec:
      containers:
        - name: elk
          image: docker.io/alialrabi/elk:latest
          ports:
            - containerPort: 8080
             
