apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  elasticsearch.yml: |
    cluster.name: elk-cluster
    network.host: 0.0.0.0
    xpack.security.enabled: false
    discovery.type: single-node




